# Numpy

Python作为深度学习最主流的编程语言，在深度学习工程具体实现中提供了Numpy库(Numerical Python extensions)来作为工具，帮助使用者实现深度学习神经网络，甚至用于实现深度学习框架。

Numpy是一个第三方的Python包，用于科学计算。这个库的前身是1995年就开始开发的一个用于数组运算的库。经过了长时间的发展，基本上成了绝大部分Python科学计算的基础包，当然也包括所有提供Python接口的深度学习框架。

## 基本模块

** Array模块 **

Array，也就是数组，是numpy中最基础的数据结构。最关键的属性是维度和元素类型，在numpy中，可以非常方便地创建各种不同类型的多维数组，并且执行一些基本操作。在深度学习中，如果神经元之间的连接关系涉及到的参数是数组，便可利用Array模块进行设定，来看例子：


In [12]:
import numpy as np

a = [1, 2, 3, 4]     	# a是python中的list类型
b = np.array(a)         # 数组化之后b的类型变为 array
type(b)                  # b的类型 <type 'numpy.ndarray'>

b.shape                   # shape参数表示array的大小，这里是(4,)
b.argmax()               # 调用max()函数可以求得array中的最大值的索引，这里是3
b.max()                   # 调用max()函数可以求得array中的最大值，这里是4
b.mean()                  # 调用mean()函数可以求得array中的平均值，这里是2.5


2.5

注意到在导入numpy的时候，代码中将np作为numpy的别名。这是一种习惯性的用法，后面的章节中本书也默认这么使用。例如在机器学习中常用到的矩阵的转置操作，可以通过matrix构建矩阵，transpose函数来实现转置：


In [13]:
from numpy import matrix

x=matrix(np.arange(12).reshape((3,4)))
print("x:\n", x)
t = x.transpose()
print("transposed x:\n", t)


x:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed x:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


对于一维的array，所有Python列表（list）支持的下标操作方法array也都支持，所以在此没有特别列出。
既然叫numerical python，numpy本身所具有的基础数学运算也是强大的：


In [14]:
# 绝对值，1
a = np.abs(-1)
print("a:", a)

# sin函数，1.0
b = np.sin(np.pi/2)
print("b:", b)

# tanh逆函数，0.50000107157840523
c = np.arctanh(0.462118)
print("c:", c)

# e为底的指数函数，20.085536923187668
d = np.exp(3)
print("d:", d)

# 2的3次方，8
f = np.power(2, 3)
print("f:", f)

# 点乘，1*3+2*4=11
g = np.dot([1, 2], [3, 4])
print("g:", g)

# 开方，5
h = np.sqrt(25)
print("h:", h)

# 求和，10
l = np.sum([1, 2, 3, 4])
print("l:", l)

# 平均值，5.5
m = np.mean([4, 5, 6, 7])
print("m:", m)

# 标准差，0.96824583655185426
p = np.std([1, 2, 3, 2, 1, 3, 2, 0])
print("p:", p)


a: 1
b: 1.0
c: 0.500001071578
d: 20.0855369232
f: 8
g: 11
h: 5.0
l: 10
m: 5.5
p: 0.968245836552


** Random模块 **

numpy中的随机模块包含了随机数产生和统计分布相关的基本函数。Python本身也有随机模块random，不过numpy的random功能更丰富，随机模块一般会用于深度学习中的一些随机数的生成，seed的生成以及初始值的设定，具体的用法请看下列代码： 


In [15]:
import numpy.random as random

# 设置随机数种子
random.seed(42)

# 产生一个1x3，[0,1)之间的浮点型随机数
# array([[ 0.37454012,  0.95071431,  0.73199394]])
# 后面的例子就不在注释中给出具体结果了
random.rand(1, 3)

# 产生一个[0,1)之间的浮点型随机数
random.random()

# 从a中有放回的随机采样7个
a = np.array([1, 2, 3, 4, 5, 6, 7])
random.choice(a, 7)

# 从a中无放回的随机采样7个
random.choice(a, 7, replace=False)

# 对a进行乱序并返回一个新的array
b = random.permutation(a)
   
# 生成一个长度为9的随机bytes序列并作为str返回
# '\x96\x9d\xd1?\xe6\x18\xbb\x9a\xec'
random.bytes(9)



b'\xfc\x18\xcf\x01\xeb\xf2\x93nX'

## 广播机制

对于array，默认执行对位运算。涉及到多个array的对位运算需要array的维度一致，如果一个array的维度和另一个array的子维度一致，则在没有对齐的维度上分别执行对位运算，这种机制叫做广播（broadcasting），言语解释比较难，还是看例子理解：

In [16]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [1, 2, 3],
    [1, 2, 3]
])

'''
维度一样的array，对位计算
array([[2, 4, 6],
       [5, 7, 9]])
'''
a + b

c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
d = np.array([2, 2, 2])

'''
广播机制让计算的表达式保持简洁
d和c的每一行分别进行运算
array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])
'''
c + d


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## 向量化

向量化在深度学习中的应用十分广泛，它是提升计算效率的主要手段之一。对于在机器学习中缩短每次训练的时间是很有意义的，当可用工作时间不变的情况下，更短的单次训练时间可以让程序员有更多的测试机会，进而更早更好的调整神经网络结构和参数。接下来通过一个矩阵相乘的例子来呈现向量化对于代码计算速度的提升效果。

首先导入了numpy和time库，它们分别被用于数学计算和统计运行时间。然后准备数据，这里初始化两个1000000维的随机向量v1和v2，v作为计算结果初始化为零。

In [17]:
import numpy as np
import time
#初始化两个1000000维的随机向量v1,v2用于矩阵相乘计算
v1 = np.random.rand(1000000)	
v2 = np.random.rand(1000000)
v = 0


设置变量tic和toc分别为计算开始时间和结束时间。在非向量化版本中，两个向量相乘的计算过程使用for循环实现。

In [18]:
#矩阵相乘-非向量化版本
tic = time.time()
for i in range(1000000):
    v += v1[i]*v2[i]
toc = time.time()
print("非向量化-计算结果：" + str(v) + "ms")
print("非向量化-计算时间：" + str((toc - tic)*1000)+"ms"+"\n")

非向量化-计算结果：249918.031243ms
非向量化-计算时间：549.713134765625ms



同样使用变量tic和toc记录计算开始和结束时间。向量化版本使用numpy库的numpy.dot()计算矩阵相乘。


In [19]:
#矩阵相乘-向量化版本
tic = time.time()
v = np.dot(v1, v2)
toc = time.time()
print("向量化-计算结果：" + str(v) + "ms")
print("向量化-计算时间：" + str((toc - tic)*1000)+"ms")

向量化-计算结果：249918.031243ms
向量化-计算时间：4.447221755981445ms


可以观察到效率提升效果十分显著。非向量化版本的计算时间约为向量化版本计算时间的500倍。可见向量化对于计算速度的提升是很明显的，尤其是在长时间的深度学习训练中，向量化可以帮助开发者节省更多时间。